### ISSUE TITLE
net.epson.epsonscan2 cannot find scanner connected via USB

### ISSUE THREAD

**Issue by markman8** [flathub/net.epson.epsonscan2#12]
Flatpak version
1.15.6

What Linux distribution are you using?
openSUSE

Linux distribution version
Tumbleweed

What architecture are you using?
x86_64

How to reproduce

1. flatpak run net.epson.epsonscan2
2. The window for selecting the scanner appears yet cannot detect the EPSON Perfection 4490 PHOTO scanner that is connected via USB on the laptop.
3. Running scanimage -L finds the same scanner and outputs: device `epkowa:interpreter:002:005’ is a Epson Perfection 4490 flatbed scanner

Expected Behavior
I expected by the time the proprietary drivers for EPSON for linux are already installed on the system and as scanimage -L and iscan program runs and scans images with the same set up that the flatpak run net.epson.epsonscan2 program should detect the scanner at least...

Actual Behavior
The application runs yet it does not detect the scanner.

`mark@pc-42:~> lsusb
Bus 001 Device 002: ID 8087:8001 Intel Corp. Integrated Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 003 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 002 Device 004: ID 8087:0a2a Intel Corp. Bluetooth wireless interface
Bus 002 Device 003: ID 138a:0017 Validity Sensors, Inc. VFS 5011 fingerprint sensor
Bus 002 Device 002: ID 04f3:012d Elan Microelectronics Corp. Touchscreen
Bus 002 Device 005: ID 04b8:0119 Seiko Epson Corp. GT-X750 [Perfection 4490 Photo]
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
mark@pc-42:~> flatpak run net.
net.displaycal.DisplayCAL net.epson.epsonscan2 net.sourceforge.qtpfsgui.LuminanceHDR
mark@pc-42:~> flatpak run net.epson.epsonscan2
Qt: Session management error: Could not open network socket
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
mark@pc-42:~> flatpak run net.epson.epsonscan2 -l
Device is not found…

mark@pc-42:~> scanimage -L
device `epkowa:interpreter:002:005’ is a Epson Perfection 4490 flatbed scanner`

**Comment by hfiguiere** [comment]
I don't see this scanner on the list.

**Comment by hfiguiere** [comment]
Nothing we can do about.
