### ISSUE TITLE
crashes on start 

### ISSUE THREAD

**Issue by saikatm** [flathub/net.epson.epsonscan2#2]
OS:  Nobara Linux 36 (Thirty Six) 
kernel:  5.19.16-201.fsync.fc36.x86_64 

I don't know how to collect crash logs please help me out.

**Comment by hfiguiere** [comment]
looks like #1

**Comment by hfiguiere** [comment]
It's likely because it can't find the scanner. (crash is fixed in #3, bug from Epson)
