### ISSUE TITLE
epson not update archive page of .src.tar.gz file

### ISSUE THREAD

**Issue by dasaferi** [flathub/net.epson.epsonscan2#8]
Hello hfiguiere the epson site (https://support.epson.net/linux/src/scanner/epsonscan2/) no longer contains the recent versions and as if they have abandoned it, now they are only here https://support.epson.net/linux/en/epsonscan2.php and you need to click on the sentence at the bottom of the page `If you want to use the driver other than the above distribution,
we recommend that you build from the source file and install it.` so the download of the .src.tar.gz file will start.

**Comment by hfiguiere** [comment]
what the purpose of this issue?

**Comment by dasaferi** [comment]
I opened this issue to warn you that the old archive we used to update the flatpak can no longer be used, I see that you have found a workaround. if there will be new versions i will try to send PR with the new site.
